<?php
/**
 * MediaMosa is a Full Featured, Webservice Oriented Media Management and
 * Distribution platform (http://www.vpcore.nl)
 *
 * Copyright (C) 2009 SURFnet BV (http://www.surfnet.nl) and Kennisnet
 * (http://www.kennisnet.nl)
 *
 * MediaMosa is based on the open source Drupal platform and
 * was originally developed by Madcap BV (http://www.madcap.nl)
 *
 * mediamosa_client offers a communication wrapper to a MediaMosa server
 * and was originally developed by Synetic BV (http://www.synetic.nl)
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation.
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, you can find it at:
 * http://www.gnu.org/licenses/old-licenses/gpl-2.0.html
 */

/**
 * @file
 * This module contains a class for handling communication with a mediamosa
 * server
 */

/**
 * Retrieve an instance of the client class.
 * 
 * A static variable is used to ensure only one instance of this class.
 * 
 * @return mediamosa_client instance
 */
function mediamosa_client_get_client() {
  static $mediamosa_client;
  if (empty($mediamosa_client)) {
    require_once drupal_get_path('module', 'mediamosa_client') . '/classes/mediamosa_client.class.inc';
    $mediamosa_client = new mediamosa_client();
  }
  return $mediamosa_client;
}